sudo: required
language: php
dist: trusty

php:
  - 7.3

install:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -e 'create database testing;'
  - php artisan serve &

script:
  - php artisan key:generate
  - php artisan migrate
  - vendor/bin/phpunit
