name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks you, We will look into as soon as possible."
        pr-message: "Welcome. Thanks for the pull request. We appreciate your contribution. We will review your pull request and get back to you as soon as possible."
